"""Installer Hardening — exec-12 Phase 2.7
Replace default/placeholder credentials in .env with cryptographically secure values.
Idempotent: only replaces known default values, never overwrites real credentials.

Usage:
  uv run python scripts/harden-env.py                    # Harden python-backend/.env
  uv run python scripts/harden-env.py --env-file .env    # Specify path
  uv run python scripts/harden-env.py --dry-run           # Show changes without writing

Pattern: pentagi installer hardening (idempotent, sync dependent vars)
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import string
import sys
from pathlib import Path

# ── Default values that must be replaced ─────────────────────────────────────

# { ENV_VAR_NAME: list_of_known_insecure_defaults }
# If the current value matches any default, it gets replaced.
INSECURE_DEFAULTS: dict[str, list[str]] = {
    # LiveKit
    "LIVEKIT_API_KEY": ["devkey", ""],
    "LIVEKIT_API_SECRET": ["change-in-production", "secret", ""],
    # Matrix Bot
    "MATRIX_BOT_PASSWORD": ["", "changeme", "password"],
    "MATRIX_BOT_ACCESS_TOKEN": [""],
    # Database (when uncommented)
    "HINDSIGHT_DB_URL": [],  # Skip — connection strings are complex
    "AUDIT_DB_URL": [],      # Skip
}

# Variables that should be generated if empty (but not if they have any value)
GENERATE_IF_EMPTY: dict[str, str] = {
    "ANTHROPIC_API_KEY": "skip",   # User must provide, don't generate
    "OPENAI_API_KEY": "skip",      # User must provide, don't generate
    "MATRIX_BOT_PASSWORD": "alphanum",
    "MATRIX_BOT_ACCESS_TOKEN": "skip",  # Generated by Matrix server
    "LIVEKIT_API_KEY": "alphanum",
    "LIVEKIT_API_SECRET": "alphanum_long",
}


def generate_secret(style: str) -> str:
    """Generate a cryptographically secure random value."""
    if style == "alphanum":
        alphabet = string.ascii_letters + string.digits
        return "".join(secrets.choice(alphabet) for _ in range(24))
    if style == "alphanum_long":
        alphabet = string.ascii_letters + string.digits
        return "".join(secrets.choice(alphabet) for _ in range(36))
    if style == "hex":
        return secrets.token_hex(16)
    if style == "hex_long":
        return secrets.token_hex(32)
    if style == "skip":
        return ""
    return secrets.token_urlsafe(24)


def is_insecure(var_name: str, value: str) -> bool:
    """Check if a value is a known insecure default."""
    defaults = INSECURE_DEFAULTS.get(var_name, [])
    return value in defaults


def harden_env(env_path: Path, *, dry_run: bool = False) -> list[str]:
    """Read .env, replace insecure defaults, return list of changes made."""
    if not env_path.exists():
        print(f"ERROR: {env_path} does not exist")
        print(f"  Copy .env.example to .env first:")
        print(f"    cp {env_path.parent / '.env.example'} {env_path}")
        sys.exit(1)

    content = env_path.read_text(encoding="utf-8")
    lines = content.splitlines(keepends=True)
    changes: list[str] = []
    new_lines: list[str] = []

    for line in lines:
        # Skip comments and empty lines
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue

        # Parse KEY=VALUE (handle quoted values)
        match = re.match(r"^([A-Z_][A-Z0-9_]*)=(.*)$", stripped)
        if not match:
            new_lines.append(line)
            continue

        key, value = match.group(1), match.group(2)
        # Strip quotes
        if (value.startswith('"') and value.endswith('"')) or \
           (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]

        # Check if this variable needs hardening
        if key in INSECURE_DEFAULTS and is_insecure(key, value):
            style = GENERATE_IF_EMPTY.get(key, "alphanum")
            if style == "skip":
                new_lines.append(line)
                continue

            new_value = generate_secret(style)
            changes.append(f"  {key}: '{value}' -> '{new_value[:8]}...{new_value[-4:]}'")

            # Preserve original line format (indentation, comments)
            new_line = f"{key}={new_value}\n"
            new_lines.append(new_line)
        elif key in GENERATE_IF_EMPTY and not value:
            style = GENERATE_IF_EMPTY[key]
            if style == "skip":
                new_lines.append(line)
                continue

            new_value = generate_secret(style)
            changes.append(f"  {key}: (empty) -> '{new_value[:8]}...{new_value[-4:]}'")
            new_line = f"{key}={new_value}\n"
            new_lines.append(new_line)
        else:
            new_lines.append(line)

    if not changes:
        print("No insecure defaults found. .env looks good.")
        return changes

    print(f"{'[DRY RUN] ' if dry_run else ''}Changes ({len(changes)}):")
    for change in changes:
        print(change)

    if not dry_run:
        # Backup original
        backup_path = env_path.with_suffix(".env.bak")
        env_path.rename(backup_path)
        print(f"\n  Backup: {backup_path}")

        # Write hardened version
        env_path.write_text("".join(new_lines), encoding="utf-8")
        print(f"  Written: {env_path}")
    else:
        print("\n  (dry run — no files changed)")

    return changes


def main():
    parser = argparse.ArgumentParser(description="Harden .env credentials")
    parser.add_argument(
        "--env-file",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "python-backend" / ".env",
        help="Path to .env file (default: python-backend/.env)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show changes without writing",
    )
    args = parser.parse_args()

    print(f"Hardening: {args.env_file}")
    print()
    harden_env(args.env_file, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
